name: MirrorThemAll

on:
  push:
    branches:
    - master
  schedule:
    - cron:  '30 05 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Fetch and push zm-build
      run: |
           ZIMBRA_REPOS="\
           adminguide \
           ant-1.7.0-ziputil-patched \
           antisamy \
           ant-tar-patched \
           asciidoctor-stylesheet-factory \
           clipboard.js \
           Collaboration-Zimlets \
           docker-zcs-dev-machine \
           docker-zcs-foss \
           docker-zcs-foss-test \
           docker-zcs-soap-tests \
           docker-zcs-solr-test \
           ical4j-0.9.16-patched \
           installguides \
           java-html-sanitizer \
           java-html-sanitizer-release-20190610.1 \
           Mezeo-Vendor-Storage-Module-SDK \
           nekohtml-1.9.13 \
           nginx \
           oauth2_datasources \
           packages \
           qless-java \
           simioj \
           vagrant-provision-zimbra \
           weather-sync \
           zd-full \
           zimbra-admin-ui-ember \
           zimbra-bugzilla-scrum \
           zimbra-build \
           zimbra-client \
           zimbra-ml \
           zimbra-package-stub \
           zimlet-cli \
           zm-admin-ajax \
           zm-admin-console \
           zm-admin-help-common \
           zm-ajax \
           zm-amavis \
           zm-api-js-client \
           zm-api-test-harness \
           zm-aspell \
           zm-base-os \
           zm-build \
           zm-bulkprovision-admin-zimlet \
           zm-bulkprovision-store \
           zm-captcha-service \
           zm-certificate-manager-admin-zimlet \
           zm-certificate-manager-store \
           zm-charset \
           zm-clam-scanner-store \
           zm-clientuploader-admin-zimlet \
           zm-clientuploader-store \
           zm-core-utils \
           zm-db-conf \
           zm-dev-utils \
           zm-dnscache \
           zm-docker \
           zm-docker-1 \
           zm-docker-base \
           zm-downloads \
           zm-freshclam \
           zm-genesis \
           zm-gql \
           zm-help \
           zm-helptooltip-zimlet \
           zm-jetty-conf \
           zm-jython \
           zm-launcher \
           zm-ldap-utilities \
           zm-ldap-utils-store \
           zm-licenses \
           zm-load \
           zm-load-testing \
           zm-mailbox \
           zm-migration-tools \
           zm-mta \
           zm-nginx-conf \
           zm-nginx-lookup-store \
           zm-oauth-social \
           zm-openid-consumer-store \
           zm-pkg-tool \
           zm-postfix \
           zm-proxy-config-admin-zimlet \
           zm-repo-tool \
           zm-selenium \
           zm-solr \
           zm-solr-docker \
           zm-ssdb-ephemeral-store \
           zm-taglib \
           zm-timezones \
           zm-versioncheck-admin-zimlet \
           zm-versioncheck-store \
           zm-versioncheck-utilities \
           zm-viewmail-admin-zimlet \
           zm-web-client \
           zm-web-client-help \
           zm-webclient-portal-example \
           zm-wsdl-test \
           zm-x-client-proxy \
           zm-x-ui \
           zm-x-zimlet-template-default \
           zm-zcs \
           zm-zcs-lib \
           zm-zcs-test \
           zm-zextras \
           zm-zimlets \
           "
           mkdir tmp-repo
           cd tmp-repo
           for nrepo in ${ZIMBRA_REPOS}; do
             git config --global user.name "Maldua-mirror via GitHub Actions"
             git clone --bare https://github.com/Zimbra/${nrepo}.git
             cd ${nrepo}.git
             git remote add malduamirror https://x-access-token:$GITHUB_TOKEN@github.com/maldua-mirror/${nrepo}.git
             git push --mirror malduamirror
             cd ..
           done
      env:
        GITHUB_TOKEN: ${{ secrets.MALDUAMIRROR_TOKEN }}
