name: CI

on:
  push:
    branches:
    - update-mirror

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Fetch and push zm-build
      run: |
           mkdir tmp-repo
           cd tmp-repo
           git clone --bare git@github.com:Zimbra/zm-build.git
           cd zm-build.git
           git remote add malduamirror git@github.com:maldua-mirror/zm-build.git
           git push --mirror malduamirror
