name: MirrorThemAll

on:
  push:
    branches:
    - master
  schedule:
    - cron:  '36 16 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Fetch and push zm-build
      run: |
           ZIMBRA_REPOS="zm-build zm-zcs-lib"
           for nrepo in ${ZIMBRA_REPOS}; do
             mkdir tmp-repo
             cd tmp-repo
             git config --global user.name "Maldua-mirror via GitHub Actions"
             git clone --bare https://github.com/Zimbra/${nrepo}.git
             cd zm-build.git
             git remote add malduamirror https://x-access-token:$GITHUB_TOKEN@github.com/maldua-mirror/${nrepo}.git
             git push --mirror malduamirror
           done
      env:
        GITHUB_TOKEN: ${{ secrets.MALDUAMIRROR_TOKEN }}
